# Local Development Docker Compose
# This file maintains compatibility with local development
# while the AWS version uses dynamic service discovery

version: '3.8'

services:
  # MapReduce Master 0
  master0:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["./mapreduce", "master", "0", "/root/data/Words.txt"]
    ports:
      - "1234:1234" # Raft
      - "8000:8000" # RPC
      - "8100:8100" # Health check
      - "9090:9090" # Metrics
    environment:
      - RAFT_ADDRESSES=master0:1234,master1:1234,master2:1234
      - RPC_ADDRESSES=master0:8000,master1:8001,master2:8002
      - TMP_PATH=/tmp/mapreduce
      - METRICS_ENABLED=true
      - METRICS_PORT=9090
      - MAPREDUCE_MASTER_TASK_TIMEOUT=120s
      - MAPREDUCE_MASTER_HEARTBEAT_INTERVAL=5s
      - MAPREDUCE_WORKER_RETRY_INTERVAL=2s
      - WORKER_COUNT=3
      - DEPLOYMENT_ENV=local
      - LOCAL_MODE=true
    volumes:
      - intermediate-data:/tmp/mapreduce
      - ${PWD}/data:/root/data
    networks:
      - mapreduce-net
    restart: unless-stopped
    stop_grace_period: 30s

  # MapReduce Master 1
  master1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["./mapreduce", "master", "1", "/root/data/Words.txt"]
    ports:
      - "1235:1234"
      - "8001:8001"
      - "8101:8101" # Health check
    environment:
      - RAFT_ADDRESSES=master0:1234,master1:1234,master2:1234
      - RPC_ADDRESSES=master0:8000,master1:8001,master2:8002
      - TMP_PATH=/tmp/mapreduce
      - METRICS_ENABLED=true
      - METRICS_PORT=9090
      - MAPREDUCE_MASTER_TASK_TIMEOUT=120s
      - MAPREDUCE_MASTER_HEARTBEAT_INTERVAL=5s
      - MAPREDUCE_WORKER_RETRY_INTERVAL=2s
      - WORKER_COUNT=3
      - DEPLOYMENT_ENV=local
      - LOCAL_MODE=true
    volumes:
      - intermediate-data:/tmp/mapreduce
      - ${PWD}/data:/root/data
    networks:
      - mapreduce-net
    restart: unless-stopped
    stop_grace_period: 30s

  # MapReduce Master 2
  master2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["./mapreduce", "master", "2", "/root/data/Words.txt"]
    ports:
      - "1236:1234"
      - "8002:8002"
      - "8102:8102" # Health check
    environment:
      - RAFT_ADDRESSES=master0:1234,master1:1234,master2:1234
      - RPC_ADDRESSES=master0:8000,master1:8001,master2:8002
      - TMP_PATH=/tmp/mapreduce
      - METRICS_ENABLED=true
      - METRICS_PORT=9090
      - MAPREDUCE_MASTER_TASK_TIMEOUT=120s
      - MAPREDUCE_MASTER_HEARTBEAT_INTERVAL=5s
      - MAPREDUCE_WORKER_RETRY_INTERVAL=2s
      - WORKER_COUNT=3
      - DEPLOYMENT_ENV=local
      - LOCAL_MODE=true
    volumes:
      - intermediate-data:/tmp/mapreduce
      - ${PWD}/data:/root/data
    networks:
      - mapreduce-net
    restart: unless-stopped
    stop_grace_period: 30s

  # MapReduce Worker 1
  worker1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["./mapreduce", "worker"]
    ports:
      - "8081:8081"
    environment:
      - RAFT_ADDRESSES=master0:1234,master1:1234,master2:1234
      - RPC_ADDRESSES=master0:8000,master1:8001,master2:8002
      - TMP_PATH=/tmp/mapreduce
      - METRICS_ENABLED=true
      - METRICS_PORT=9090
      - MAPREDUCE_MASTER_TASK_TIMEOUT=120s
      - MAPREDUCE_MASTER_HEARTBEAT_INTERVAL=5s
      - MAPREDUCE_WORKER_RETRY_INTERVAL=2s
      - WORKER_COUNT=3
      - DEPLOYMENT_ENV=local
      - LOCAL_MODE=true
    volumes:
      - intermediate-data:/tmp/mapreduce
      - ${PWD}/data:/root/data
    networks:
      - mapreduce-net
    restart: unless-stopped
    stop_grace_period: 30s

  # MapReduce Worker 2
  worker2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["./mapreduce", "worker"]
    ports:
      - "8082:8081"
    environment:
      - RAFT_ADDRESSES=master0:1234,master1:1234,master2:1234
      - RPC_ADDRESSES=master0:8000,master1:8001,master2:8002
      - TMP_PATH=/tmp/mapreduce
      - METRICS_ENABLED=true
      - METRICS_PORT=9090
      - MAPREDUCE_MASTER_TASK_TIMEOUT=120s
      - MAPREDUCE_MASTER_HEARTBEAT_INTERVAL=5s
      - MAPREDUCE_WORKER_RETRY_INTERVAL=2s
      - WORKER_COUNT=3
      - DEPLOYMENT_ENV=local
      - LOCAL_MODE=true
    volumes:
      - intermediate-data:/tmp/mapreduce
      - ${PWD}/data:/root/data
    networks:
      - mapreduce-net
    restart: unless-stopped
    stop_grace_period: 30s

  # MapReduce Worker 3
  worker3:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["./mapreduce", "worker"]
    ports:
      - "8083:8081"
    environment:
      - RAFT_ADDRESSES=master0:1234,master1:1234,master2:1234
      - RPC_ADDRESSES=master0:8000,master1:8001,master2:8002
      - TMP_PATH=/tmp/mapreduce
      - METRICS_ENABLED=true
      - METRICS_PORT=9090
      - MAPREDUCE_MASTER_TASK_TIMEOUT=120s
      - MAPREDUCE_MASTER_HEARTBEAT_INTERVAL=5s
      - MAPREDUCE_WORKER_RETRY_INTERVAL=2s
      - WORKER_COUNT=3
      - DEPLOYMENT_ENV=local
      - LOCAL_MODE=true
    volumes:
      - intermediate-data:/tmp/mapreduce
      - ${PWD}/data:/root/data
    networks:
      - mapreduce-net
    restart: unless-stopped
    stop_grace_period: 30s

  # MapReduce Dashboard
  dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["./mapreduce", "dashboard", "--port", "8080"]
    depends_on: ["master0", "master1", "master2"]
    networks:
      - mapreduce-net
    ports:
      - "8080:8080"
    volumes:
      - intermediate-data:/tmp/mapreduce
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RAFT_ADDRESSES=master0:1234,master1:1234,master2:1234
      - RPC_ADDRESSES=master0:8000,master1:8001,master2:8002
      - TMP_PATH=/tmp/mapreduce
      - METRICS_ENABLED=true
      - DEPLOYMENT_ENV=local
      - LOCAL_MODE=true
    restart: unless-stopped
    stop_grace_period: 30s

networks:
  mapreduce-net:
    driver: bridge

volumes:
  intermediate-data:
    driver: local
